# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ENOL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ENOL
  pod 'Alamofire', '~> 4.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'AWSCore'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'SKActivityIndicatorView', '~> 1.0.0'
  pod 'GoogleMaps'
  pod ‘GooglePlaces’
end
